/**
 * The project document: where a project's declared facts live (OpenWorkspace
 * decision-3, amending decision-2).
 *
 * A project's declared facts — the information map (`[map]`), `lifecycle`,
 * `[[owns]]` edges — live in ONE of two places, never both:
 *
 *  - **Folder project**: `_project/project.toml`, identity in `_project/id`.
 *    Every project that uses a native store (or predates map-only projects)
 *    is a folder project. Unchanged from decision-2.
 *  - **Map-only project**: no `_project/` folder at all. The facts live in a
 *    fenced TOML block inside the generated "Where information lives" block
 *    of the project's README.md (or AGENTS.md when README.md carries none),
 *    together with the project's identity:
 *
 *        <!-- BEGIN openworkspace:information-map map-only (…) -->
 *        ## Where information lives
 *        …human-readable lines…
 *        ```toml
 *        format = "openworkspace-map/1"
 *        uid = "4f0c2d8e-…"
 *
 *        [map.tasks]
 *        system = "Teamwork"
 *        locator = "unknown"
 *        ```
 *        <!-- END openworkspace:information-map -->
 *
 * Detection is deliberately strict so a document that merely DESCRIBES the
 * format is never mistaken for a project: the BEGIN and END marker lines must
 * start at column 0 OUTSIDE any fenced code block, the BEGIN line must carry
 * the `map-only` flavor, and the block must contain a fenced TOML block whose
 * `format` is `openworkspace-map/1` and whose `uid` is a UUID. Only README.md
 * and AGENTS.md at the directory itself are candidates.
 *
 * The folder wins: a directory with `_project/id` is a folder project and any
 * map-only block in its docs is just a stale rendering (`projects map render`
 * rewrites it). Of README.md and AGENTS.md, the first carrying a valid block
 * is the SOURCE (the one source of truth); the other is a rendered copy.
 *
 * This module is low-level on purpose (fs + toml only) so both workspace.ts
 * (identity, lifecycle, owns) and infomap.ts (the map) can build on it.
 */

import * as fs from "node:fs";
import * as path from "node:path";

import { ConfigError } from "./errors.js";
import { readTextIfExists, writeFileAtomic } from "./fsatomic.js";
import { TomlTable, parseToml, readTomlIfExists, stringifyToml, writeToml } from "./toml.js";

// ---------------------------------------------------------------------------
// Markers

/** Every information-map block starts with a line beginning with this. */
export const MAP_BEGIN_PREFIX = "<!-- BEGIN openworkspace:information-map";

/** The BEGIN line of a folder project's rendered block (decision-2; unchanged). */
export const MAP_BEGIN =
  "<!-- BEGIN openworkspace:information-map (generated by `projects map render` from _project/project.toml [map]; edit the map, not this block) -->";

/** The BEGIN line of a map-only project's block (the block IS the map). */
export const MAP_BEGIN_MAP_ONLY =
  "<!-- BEGIN openworkspace:information-map map-only (this block is the project's information map and its source of truth: the TOML below is parsed by the `projects` CLI; change it with `projects map set`, or edit the TOML and run `projects map render`) -->";

export const MAP_END = "<!-- END openworkspace:information-map -->";

/** The embedded document's format tag. */
export const MAP_ONLY_FORMAT = "openworkspace-map/1";

/** Docs that may carry a map-only project's source block, in precedence order. */
export const MAP_ONLY_CANDIDATES: readonly string[] = ["README.md", "AGENTS.md"];

/** Keys of the embedded document that are identity/format, not project.toml facts. */
export const MAP_ONLY_IDENTITY_KEYS: readonly string[] = ["format", "uid"];

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/** Skip absurdly large docs (never a map-only README worth parsing). */
const MAX_DOC_BYTES = 2 * 1024 * 1024;

// ---------------------------------------------------------------------------
// Fence-aware block location

export interface MapBlock {
  /** Char offset of the BEGIN line's first character. */
  start: number;
  /** Char offset just past the END marker. */
  end: number;
  /** The full BEGIN line (without its newline). */
  beginLine: string;
  /** Text between the BEGIN line and the END marker (one leading/trailing newline stripped). */
  body: string;
  /** True when the BEGIN line carries the map-only flavor. */
  mapOnly: boolean;
}

const FENCE_RE = /^ {0,3}(`{3,}|~{3,})(.*)$/;

/**
 * Find the first information-map block whose BEGIN and END marker lines sit at
 * column 0 outside any fenced code block. Returns null when there is none (a
 * BEGIN without a matching END is not a block).
 */
export function findMapBlock(text: string): MapBlock | null {
  let offset = 0;
  let fence: string | null = null;
  let begin: { start: number; line: string; bodyStart: number } | null = null;
  while (offset <= text.length) {
    const nl = text.indexOf("\n", offset);
    const lineEnd = nl === -1 ? text.length : nl;
    const raw = text.slice(offset, lineEnd);
    const line = raw.endsWith("\r") ? raw.slice(0, -1) : raw;
    const m = FENCE_RE.exec(line);
    if (fence !== null) {
      // A closing fence: same char, at least as long, nothing but whitespace after.
      if (m !== null && m[1] !== undefined && m[1][0] === fence[0] && m[1].length >= fence.length && (m[2] ?? "").trim() === "") {
        fence = null;
      }
    } else if (m !== null && m[1] !== undefined) {
      fence = m[1];
    } else if (begin === null) {
      if (line.startsWith(MAP_BEGIN_PREFIX)) begin = { start: offset, line, bodyStart: nl === -1 ? lineEnd : nl + 1 };
    } else if (line.startsWith(MAP_END)) {
      const body = text.slice(begin.bodyStart, offset).replace(/\r?\n$/, "");
      return {
        start: begin.start,
        end: offset + MAP_END.length,
        beginLine: begin.line,
        body,
        mapOnly: begin.line.startsWith(MAP_BEGIN_PREFIX + " map-only"),
      };
    }
    if (nl === -1) break;
    offset = nl + 1;
  }
  return null;
}

/** Compose a block from its BEGIN line and body. */
export function composeBlock(beginLine: string, body: string): string {
  return `${beginLine}\n${body}\n${MAP_END}`;
}

/**
 * Replace (or append) the information-map block in a document. Idempotent;
 * text outside the markers is preserved byte-for-byte. Either flavor of an
 * existing block is replaced (a folder project's render overwrites a stale
 * map-only block and vice versa).
 */
export function applyBlock(current: string, block: string): string {
  const found = findMapBlock(current);
  if (found !== null) {
    let next = current.slice(0, found.start) + block + current.slice(found.end);
    if (!next.endsWith("\n")) next += "\n";
    return next;
  }
  let base = current;
  if (base.length > 0 && !base.endsWith("\n")) base += "\n";
  if (base.length > 0 && !base.endsWith("\n\n")) base += "\n";
  return base + block + "\n";
}

// ---------------------------------------------------------------------------
// The embedded TOML

const TOML_FENCE_OPEN = /^(`{3,}|~{3,})\s*toml\s*$/;

/** Locate the first ```toml fence inside a block body: its content and char range. */
function findTomlFence(body: string): { content: string; start: number; end: number } | null {
  const lines = body.split("\n");
  let offset = 0;
  for (let i = 0; i < lines.length; i++) {
    const line = (lines[i] as string).replace(/\r$/, "");
    const m = TOML_FENCE_OPEN.exec(line);
    if (m !== null && m[1] !== undefined) {
      const fence = m[1];
      const contentStart = offset + (lines[i] as string).length + 1;
      let inner = contentStart;
      for (let j = i + 1; j < lines.length; j++) {
        const l = (lines[j] as string).replace(/\r$/, "").trim();
        const close = /^(`{3,}|~{3,})$/.exec(l);
        if (close !== null && close[1] !== undefined && close[1][0] === fence[0] && close[1].length >= fence.length) {
          return { content: body.slice(contentStart, inner), start: offset, end: inner + (lines[j] as string).length };
        }
        inner += (lines[j] as string).length + 1;
      }
      return null; // unclosed
    }
    offset += (lines[i] as string).length + 1;
  }
  return null;
}

/** Header comment written above the embedded TOML (rewritten on every write). */
const EMBEDDED_HEADER =
  "# OpenWorkspace map-only project: this TOML is the project's information map (source of truth).\n" +
  "# No _project/ folder exists; enabling a native store creates one and moves this map into _project/project.toml.\n";

/** Serialize the embedded document (format + uid first, then the rest in order). */
export function stringifyEmbedded(raw: TomlTable): string {
  const ordered: TomlTable = { format: MAP_ONLY_FORMAT, uid: raw["uid"] };
  for (const [k, v] of Object.entries(raw)) if (!(k in ordered)) ordered[k] = v;
  return EMBEDDED_HEADER + stringifyToml(ordered);
}

/** The fenced form of the embedded document (as it appears inside the block body). */
export function embeddedFence(raw: TomlTable): string {
  return "```toml\n" + stringifyEmbedded(raw).replace(/\n$/, "") + "\n```";
}

export interface MapOnlyDoc {
  /** Project-root-relative doc carrying the source block. */
  file: string;
  uid: string;
  /** The embedded document (format/uid included); {} when unparseable. */
  raw: TomlTable;
  /** Parse problems (an unparseable embedded TOML keeps its identity via a uid scan). */
  problems: string[];
}

/**
 * Parse a document's text as a map-only source. Returns null unless it holds a
 * valid map-only block (strict: see the module comment). An embedded TOML that
 * no longer parses still yields its uid (by a line scan) with a problem, so a
 * typo never makes the project vanish from discovery.
 */
export function parseMapOnlyText(text: string, file: string): MapOnlyDoc | null {
  if (!text.includes(MAP_BEGIN_PREFIX)) return null;
  const block = findMapBlock(text);
  if (block === null || !block.mapOnly) return null;
  const fence = findTomlFence(block.body);
  if (fence === null) return null;
  const formatLine = /^\s*format\s*=\s*["']([^"']+)["']\s*(#.*)?$/m.exec(fence.content);
  if (formatLine === null || formatLine[1] !== MAP_ONLY_FORMAT) return null;
  try {
    const raw = parseToml(fence.content, file);
    const uid = raw["uid"];
    if (typeof uid !== "string" || !UUID_RE.test(uid)) return null;
    return { file, uid, raw, problems: [] };
  } catch (err) {
    const m = /^\s*uid\s*=\s*["']([^"']+)["']/m.exec(fence.content);
    if (m === null || m[1] === undefined || !UUID_RE.test(m[1])) return null;
    return { file, uid: m[1], raw: {}, problems: [`unparseable map TOML in ${file}: ${(err as Error).message}`] };
  }
}

function readDocText(abs: string): string | null {
  try {
    const st = fs.statSync(abs);
    if (!st.isFile() || st.size > MAX_DOC_BYTES) return null;
    return fs.readFileSync(abs, "utf8");
  } catch {
    return null;
  }
}

/** The map-only source doc of `dir` (README.md, then AGENTS.md), or null. */
export function readMapOnlyDoc(dir: string): MapOnlyDoc | null {
  for (const rel of MAP_ONLY_CANDIDATES) {
    const text = readDocText(path.join(dir, rel));
    if (text === null) continue;
    const doc = parseMapOnlyText(text, rel);
    if (doc !== null) return doc;
  }
  return null;
}

// ---------------------------------------------------------------------------
// Identity

/** `_project/id` of `dir` (a folder project), or null. */
export function folderProjectUid(dir: string): string | null {
  try {
    const text = fs.readFileSync(path.join(dir, "_project", "id"), "utf8").trim();
    return text.length > 0 ? text : null;
  } catch {
    return null;
  }
}

export type ProjectForm = "folder" | "map-only";

/** A directory's project identity and form, or null when it is not a project. */
export function projectIdentity(dir: string): { uid: string; form: ProjectForm } | null {
  const folder = folderProjectUid(dir);
  if (folder !== null) return { uid: folder, form: "folder" };
  const doc = readMapOnlyDoc(dir);
  return doc !== null ? { uid: doc.uid, form: "map-only" } : null;
}

/** True when `dir` is a map-only project (no `_project/id`, a valid map-only block). */
export function isMapOnlyProject(dir: string): boolean {
  return folderProjectUid(dir) === null && readMapOnlyDoc(dir) !== null;
}

// ---------------------------------------------------------------------------
// The project document (read/write the declared facts, whichever form)

export interface ProjectDocument {
  form: ProjectForm | null;
  /** Project-root-relative path of the source of truth. */
  source: string;
  /** The project's uid (`_project/id`, or the block's `uid`); null when not a project. */
  uid: string | null;
  /** The declared facts (project.toml shape; identity keys stripped for map-only). */
  raw: TomlTable;
  /** Non-fatal read problems. */
  problems: string[];
}

export const PROJECT_TOML_REL = path.join("_project", "project.toml");

/**
 * Read a project's declared facts. Folder ⇒ `_project/project.toml` (throws a
 * ParseError when unparseable, exactly like `readTomlIfExists` — callers keep
 * their existing forgiving wrappers). Map-only ⇒ the embedded TOML (identity
 * keys stripped; an unparseable block reads as {} with a problem). Neither ⇒
 * `_project/project.toml` semantics (absent ⇒ {}).
 */
export function readProjectDocument(projectRoot: string): ProjectDocument {
  if (folderProjectUid(projectRoot) === null) {
    const doc = readMapOnlyDoc(projectRoot);
    if (doc !== null) {
      const raw: TomlTable = {};
      for (const [k, v] of Object.entries(doc.raw)) if (!MAP_ONLY_IDENTITY_KEYS.includes(k)) raw[k] = v;
      return { form: "map-only", source: doc.file, uid: doc.uid, raw, problems: doc.problems };
    }
  }
  const raw = readTomlIfExists(path.join(projectRoot, PROJECT_TOML_REL));
  const uid = folderProjectUid(projectRoot);
  return {
    form: uid !== null ? "folder" : null,
    source: PROJECT_TOML_REL,
    uid,
    raw,
    problems: [],
  };
}

/** Resolve a doc path through symlinks (CLAUDE.md → AGENTS.md) so writes keep the link. */
export function realDocPath(abs: string): string {
  try {
    return fs.realpathSync(abs);
  } catch {
    return abs;
  }
}

/**
 * Write a project's declared facts back to their source of truth. Folder (or
 * not-yet-a-project) ⇒ `_project/project.toml` (whole-document, tool-owned).
 * Map-only ⇒ the embedded TOML in the source doc is replaced in place, and the
 * source block is copied into every other `render_to` doc that already carries
 * a block, so the copies stay consistent. Identity keys are preserved.
 *
 * `emptyRemovesFile` keeps the folder-form "an empty document removes
 * project.toml" behaviour of the lifecycle/owns writers.
 */
export function writeProjectDocument(
  projectRoot: string,
  raw: TomlTable,
  options: { emptyRemovesFile?: boolean } = {},
): void {
  const folder = folderProjectUid(projectRoot) !== null;
  const doc = folder ? null : readMapOnlyDoc(projectRoot);
  if (doc === null) {
    const tomlPath = path.join(projectRoot, PROJECT_TOML_REL);
    if (options.emptyRemovesFile === true && Object.keys(raw).length === 0) {
      try {
        fs.unlinkSync(tomlPath);
      } catch (err) {
        if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
      }
      return;
    }
    writeToml(tomlPath, raw);
    return;
  }
  if (doc.problems.length > 0) {
    throw new ConfigError(`${doc.problems[0]} — fix the TOML block in ${doc.file} first (nothing written)`);
  }
  const full: TomlTable = { format: MAP_ONLY_FORMAT, uid: doc.uid };
  for (const [k, v] of Object.entries(raw)) if (!MAP_ONLY_IDENTITY_KEYS.includes(k)) full[k] = v;

  const sourceAbs = realDocPath(path.join(projectRoot, doc.file));
  const text = fs.readFileSync(sourceAbs, "utf8");
  const block = findMapBlock(text) as MapBlock;
  const fence = findTomlFence(block.body);
  if (fence === null) throw new ConfigError(`no TOML block in ${doc.file}'s information map`);
  const body = block.body.slice(0, fence.start) + embeddedFence(full) + block.body.slice(fence.end);
  const newBlock = composeBlock(block.beginLine, body);
  writeFileAtomic(sourceAbs, applyBlock(text, newBlock));

  // Keep rendered copies consistent (only docs that already carry a block).
  const renderTo = renderTargetsOf(full);
  const seen = new Set([sourceAbs]);
  for (const rel of renderTo) {
    const abs = realDocPath(path.resolve(projectRoot, rel));
    if (seen.has(abs)) continue;
    seen.add(abs);
    const current = readTextIfExists(abs);
    if (current === null || findMapBlock(current) === null) continue;
    const next = applyBlock(current, newBlock);
    if (next !== current) writeFileAtomic(abs, next);
  }
}

/** `[map] render_to` of a raw document, else the default (README.md, AGENTS.md). */
export function renderTargetsOf(raw: TomlTable): string[] {
  const map = raw["map"];
  if (map !== null && typeof map === "object" && !Array.isArray(map)) {
    const rt = (map as Record<string, unknown>)["render_to"];
    if (Array.isArray(rt) && rt.every((x) => typeof x === "string")) return rt as string[];
  }
  return ["README.md", "AGENTS.md"];
}
